### ISSUE TITLE
Usage? :)

### ISSUE THREAD

**Issue by ser** [rafrex/fractal#1]
Hi, maybe I am doing something wrong, but I have this:

```
<script src="fractal.js" type="text/javascript"></script>
<script type="text/javascript">
  var fractal = new Fractal(document.getElementById("frac1"));
</script>
```
and dev console says:

```
(index):227 Uncaught ReferenceError: Fractal is not defined
```

Where is my fault? :)

**Comment by rafgraph** [comment]
It’s under the `window.mandelbrotFractal.Fractal ` namespace.
https://github.com/rafgraph/fractal/blob/gh-pages/app/fractal.js#L10

**Comment by ser** [comment]
Hi, thanks, I have rewritten my invocation, but still have errors.

```
<script src="fractal.js" type="text/javascript"></script>
<script type="text/javascript">
  var fractal = new window.mandelbrotFractal.Fractal(document.getElementById("frac1"));
</script>
```
and dev console says:

```
Uncaught TypeError: canvas.getContext is not a function
```

Where is my fault? :)

**Comment by rafgraph** [comment]
Not sure... you need to make sure the `frac1` element is a canvas element, like https://github.com/rafgraph/fractal/blob/gh-pages/index.html#L51

**Comment by ser** [comment]
OK, it works now! Thanks for a hint :) :)

I had
```
<img id="xxx">
```
instead of
```
<canvas id="xxx"></canvas>
```

One more question. You have a few screenshots on README.md - what are required parameters to get them? Have you experimented a way to get a random fractal?

**Comment by rafgraph** [comment]
Don’t know... the `maxEscapeTime` Was probably 896 or 1792. They were created using https://fractal.rafgraph.dev
